/** Every user-visible string lives here (English only). No literals in JSX. */
export const S = {
  appName: 'Intervo',
  install: 'Install',
  updateAvailable: 'A new version is ready.',
  updateReload: 'Reload',
  updateDismiss: 'Later',

  quick: 'Quick',
  routine: 'Routine',
  work: 'Work',
  restBetweenRounds: 'Rest between rounds',
  restBetweenExercises: 'Rest between exercises',
  rounds: 'Rounds',
  getReady: 'Get ready',
  none: 'None',
  custom: 'Custom',
  total: 'Total',
  start: 'Start',
  startRoutine: 'Start routine',
  settings: 'Settings',
  history: 'History',
  closeLabel: 'Close',

  exercises: 'Exercises',
  addExercise: 'Add exercise',
  removeExercise: 'Remove',
  moveUp: 'Move up',
  moveDown: 'Move down',
  exerciseName: 'Exercise name',
  routineName: 'Routine name',
  saveRoutine: 'Save',
  savedRoutines: 'Saved routines',
  loadRoutine: 'Open',
  deleteRoutine: 'Delete',
  noneSaved: 'No saved routines yet.',
  saved: 'Saved',

  enterTime: 'Set time',
  done: 'Done',
  cancel: 'Cancel',
  backspace: 'Delete digit',
  minusFive: '−5 s',
  plusFive: '+5 s',
  timeOutOfRange: 'Enter a time of at least 1 second.',

  prep: 'Get ready',
  workPhase: 'Work',
  restPhase: 'Rest',
  upNext: 'Up next',
  roundOf: (r: number, n: number) => `Round ${r} of ${n}`,
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  timeLeft: 'Left',
  pause: 'Pause',
  resume: 'Resume',
  skip: 'Skip',
  previous: 'Back',
  addTen: '+10 s',
  confirmCancel: 'Cancel',
  confirmDeleteRoutineTitle: 'Delete this saved routine?',
  confirmDeleteRoutineBody: (name: string) => `“${name}” will be removed. This can’t be undone.`,
  confirmRemoveExerciseTitle: 'Remove this exercise?',
  confirmRemoveExerciseBody: (name: string) => `“${name}” will be removed from this routine.`,
  confirmDeleteWorkoutTitle: 'Delete this workout?',
  confirmDeleteWorkoutBody: 'It will be removed from your history and charts. This can’t be undone.',
  confirmClearTitle: 'Delete all history?',
  confirmClearBody: (n: number) => `All ${n} logged workouts will be removed. This can’t be undone.`,
  endSavedNote: 'Progress so far is saved to your history.',
  quickExercise: 'Exercise',
  quickExercisePlaceholder: 'Work',
  end: 'End',
  endConfirm: 'End this workout?',
  endYes: 'End workout',
  endNo: 'Keep going',
  finishNext: 'Finish',

  finished: 'Workout complete',
  finishedTime: 'Time',
  finishedRounds: 'Rounds',
  again: 'Do it again',
  backHome: 'Back to setup',
  viewProgress: 'View progress',
  savedToHistory: 'Saved to your history.',

  sound: 'Sound',
  soundVoice: 'Voice',
  soundBeeps: 'Beeps',
  soundSilent: 'Silent',
  vibration: 'Vibrate',
  countAloud: 'Count aloud',
  countLast3: 'Last 3 seconds',
  countEvery: 'Every second',
  countNote: 'Every second counts down out loud during work only. Rests stay quiet until the last 3 seconds.',
  voiceLabel: 'Voice',
  voiceAuto: 'Default',
  voiceFemale: 'Female',
  voiceMale: 'Male',
  voiceList: 'Choose a specific voice',
  voiceTest: 'Test voice',
  voiceTestPhrase: 'Round one. Squats. Go',
  voiceNoMatch: 'No female voice was found on this device. Pick one from the list instead.',
  voiceNoMatchMale: 'No male voice was found on this device. Pick one from the list instead.',
  voiceNone: 'No English voices were found on this device.',
  halfway: 'Call out halfway',
  sides: 'Switch sides at halfway',
  theme: 'Theme',
  themeAuto: 'Auto',
  themeLight: 'Light',
  themeDark: 'Dark',
  voiceNote: 'Voice uses your phone’s built-in speech. Keep the screen on during a workout.',
  vibrateUnsupported: 'Vibration is not available on this device.',

  historyTitle: 'History',
  back: 'Back',
  noHistory: 'No workouts logged yet. Finish or end a workout and it shows up here.',
  noMatches: 'No workouts match these filters.',
  statWorkouts: 'Workouts',
  statWorkTime: 'Work time',
  statSets: 'Sets',
  filters: 'Filters',
  dates: 'Dates',
  last7: 'Last 7 days',
  last30: 'Last 30 days',
  last90: 'Last 90 days',
  allTime: 'All time',
  customRange: 'Custom',
  dateFrom: 'From',
  dateTo: 'To',
  routineFilter: 'Routine',
  exerciseFilter: 'Exercise',
  allRoutines: 'All routines',
  allExercises: 'All exercises',
  resetFilters: 'Reset filters',
  progress: 'Progress',
  metricTime: 'Work time',
  metricSets: 'Sets',
  metricLongest: 'Longest set',
  metricSessions: 'Workouts',
  groupBy: 'Group by',
  groupDay: 'Day',
  groupWeek: 'Week',
  groupMonth: 'Month',
  weekOf: 'Week of',
  chartEmpty: 'Nothing to chart for these filters.',
  tapBar: 'Tap a bar for details.',
  completedTag: 'Completed',
  partialTag: 'Ended early',
  deleteWorkout: 'Delete',
  clearHistory: 'Delete all history',
  showMore: 'Show more',
  roundsDone: (a: number, b: number) => `${a}/${b} rounds`,
} as const;
