/** Every user-visible string lives here (English only). No literals in JSX. */
export const S = {
  appName: 'Intervo',
  install: 'Install',
  updateAvailable: 'A new version is ready.',
  updateReload: 'Reload',
  updateDismiss: 'Later',

  quick: 'Quick',
  routine: 'Routine',
  work: 'Work',
  restBetweenRounds: 'Rest between rounds',
  restBetweenExercises: 'Rest between exercises',
  rounds: 'Rounds',
  getReady: 'Get ready',
  none: 'None',
  custom: 'Custom',
  total: 'Total',
  start: 'Start',
  startRoutine: 'Start routine',
  settings: 'Settings',
  closeLabel: 'Close',

  exercises: 'Exercises',
  addExercise: 'Add exercise',
  removeExercise: 'Remove',
  moveUp: 'Move up',
  moveDown: 'Move down',
  exerciseName: 'Exercise name',
  routineName: 'Routine name',
  saveRoutine: 'Save',
  savedRoutines: 'Saved routines',
  loadRoutine: 'Open',
  deleteRoutine: 'Delete',
  noneSaved: 'No saved routines yet.',
  saved: 'Saved',

  enterTime: 'Set time',
  done: 'Done',
  cancel: 'Cancel',
  backspace: 'Delete digit',
  minusFive: '−5 s',
  plusFive: '+5 s',
  timeOutOfRange: 'Enter a time of at least 1 second.',

  prep: 'Get ready',
  workPhase: 'Work',
  restPhase: 'Rest',
  upNext: 'Up next',
  roundOf: (r: number, n: number) => `Round ${r} of ${n}`,
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  timeLeft: 'Left',
  pause: 'Pause',
  resume: 'Resume',
  skip: 'Skip',
  previous: 'Back',
  addTen: '+10 s',
  end: 'End',
  endConfirm: 'End this workout?',
  endYes: 'End workout',
  endNo: 'Keep going',
  finishNext: 'Finish',

  finished: 'Workout complete',
  finishedTime: 'Time',
  finishedRounds: 'Rounds',
  again: 'Do it again',
  backHome: 'Back to setup',

  sound: 'Sound',
  soundVoice: 'Voice',
  soundBeeps: 'Beeps',
  soundSilent: 'Silent',
  vibration: 'Vibrate',
  halfway: 'Call out halfway',
  sides: 'Switch sides at halfway',
  theme: 'Theme',
  themeAuto: 'Auto',
  themeLight: 'Light',
  themeDark: 'Dark',
  voiceNote: 'Voice uses your phone’s built-in speech. Keep the screen on during a workout.',
  vibrateUnsupported: 'Vibration is not available on this device.',
} as const;
