/** Every user-visible string lives here (English only). No literals in JSX. */
export const S = {
  appName: 'Intervo',
  install: 'Install',
  updateAvailable: 'A new version is ready.',
  updateReload: 'Reload',
  updateDismiss: 'Later',

  quick: 'Quick',
  routine: 'Routine',
  work: 'Work',
  restBetweenRounds: 'Rest between rounds',
  restBetweenExercises: 'Rest between exercises',
  rounds: 'Rounds',
  getReady: 'Get ready',
  none: 'None',
  custom: 'Custom',
  total: 'Total',
  start: 'Start',
  startRoutine: 'Start routine',
  settings: 'Settings',
  history: 'History',
  closeLabel: 'Close',

  exercises: 'Exercises',
  addExercise: 'Add exercise',
  removeExercise: 'Remove',
  moveUp: 'Move up',
  moveDown: 'Move down',
  exerciseName: 'Exercise name',
  routineName: 'Routine name',
  saveRoutine: 'Save',
  savedRoutines: 'Saved routines',
  loadRoutine: 'Open',
  deleteRoutine: 'Delete',
  noneSaved: 'No saved routines yet.',
  saved: 'Saved',

  enterTime: 'Set time',
  cancel: 'Cancel',
  backspace: 'Delete digit',
  minusFive: '−5 s',
  plusFive: '+5 s',
  timeOutOfRange: 'Enter a time of at least 1 second.',

  prep: 'Get ready',
  workPhase: 'Work',
  restPhase: 'Rest',
  upNext: 'Up next',
  roundOf: (r: number, n: number) => `Round ${r} of ${n}`,
  stepOf: (i: number, n: number) => `Step ${i} of ${n}`,
  timeLeft: 'Left',
  pause: 'Pause',
  resume: 'Resume',
  skip: 'Skip',
  previous: 'Back',
  addTen: '+10 s',
  confirmCancel: 'Cancel',
  confirmDeleteRoutineTitle: 'Delete this saved routine?',
  confirmDeleteRoutineBody: (name: string) => `“${name}” will be removed. This can’t be undone.`,
  confirmRemoveExerciseTitle: 'Remove this exercise?',
  confirmRemoveExerciseBody: (name: string) => `“${name}” will be removed from this routine.`,
  confirmDeleteWorkoutTitle: 'Delete this workout?',
  confirmDeleteWorkoutBody: 'It will be removed from your history and charts. This can’t be undone.',
  confirmClearTitle: 'Delete all history?',
  confirmClearBody: (n: number) => `All ${n} logged workouts will be removed. This can’t be undone.`,
  endSavedNote: 'Progress so far is saved to your history.',
  quickExercise: 'Exercise',
  quickExercisePlaceholder: 'Work',
  end: 'End',
  endConfirm: 'End this workout?',
  endYes: 'End workout',
  endNo: 'Keep going',
  finishNext: 'Finish',

  finished: 'Workout complete',
  finishedTime: 'Time',
  finishedRounds: 'Rounds',
  again: 'Do it again',
  backHome: 'Back to setup',
  viewProgress: 'View progress',
  savedToHistory: 'Saved to your history.',

  sound: 'Sound',
  soundVoice: 'Voice',
  soundBeeps: 'Beeps',
  soundSilent: 'Silent',
  vibration: 'Vibrate',
  countAloud: 'Count aloud',
  countLast3: 'Last 3 seconds',
  countEvery: 'Every second',
  countNote: 'Every second counts down out loud during work only. Rests stay quiet until the last 3 seconds.',
  voiceLabel: 'Voice',
  voiceAuto: 'Default',
  voiceFemale: 'Female',
  voiceMale: 'Male',
  voiceList: 'Choose a specific voice',
  voiceTest: 'Test voice',
  voiceTestPhrase: 'Round one. Squats. Go',
  voiceNoMatch: 'No female voice was found on this device. Pick one from the list instead.',
  voiceNoMatchMale: 'No male voice was found on this device. Pick one from the list instead.',
  voiceNone: 'No English voices were found on this device.',
  halfway: 'Call out halfway',
  sides: 'Switch sides at halfway',
  theme: 'Theme',
  themeAuto: 'Auto',
  themeLight: 'Light',
  themeDark: 'Dark',
  voiceNote: 'Voice uses your phone’s built-in speech. Keep the screen on during a workout.',
  vibrateUnsupported: 'Vibration is not available on this device.',

  exerciseType: 'Exercise type',
  kindTimed: 'Timed',
  kindReps: 'Reps',
  repsPerSet: 'Reps per set',
  repsTyped: 'Reps',
  repsHint: 'You tap Done when the set is finished, so the pace is yours.',
  repsUnit: 'reps',
  done: 'Done',
  repsDoneLabel: 'Reps done',
  repsMinus: 'One fewer rep',
  repsPlus: 'One more rep',
  repsSetTime: 'Set time',
  totalEstimate: 'Total (estimate)',
  metricReps: 'Total reps',
  metricBestReps: 'Best set (reps)',
  statReps: 'Reps',
  warmupTitle: 'Warm-up (optional)',
  cooldownTitle: 'Cool-down (optional)',
  warmupLabel: 'Warm-up',
  cooldownLabel: 'Cool-down',
  warmupExerciseName: 'Warm-up exercise name',
  cooldownExerciseName: 'Cool-down exercise name',
  addWarmup: 'Add warm-up exercise',
  addCooldown: 'Add cool-down exercise',
  removeBlockExercise: 'Remove',
  reorder: (name: string) => `Reorder ${name}. Drag, or press the up and down arrow keys.`,
  weightLabel: (name: string, unit: string) => `${name}: extra weight in ${unit}`,
  weightField: 'Extra weight (optional)',
  weightHint: (unit: string) => `Weight added, in ${unit}. Leave empty for bodyweight.`,
  extraSet: '+ Extra set',
  extraTag: 'extra set',
  duplicate: 'Duplicate',
  copySuffix: 'copy',
  addExamples: 'Add example routines',
  sortBy: 'Sort',
  sortRecent: 'Recent',
  sortName: 'A to Z',
  sortAdded: 'Newest',
  lastDoneNever: 'Not done yet',
  lastDone: (when: string, n: number) => `Last done ${when}${n > 0 ? ` · ${n}× in 30 days` : ''}`,
  today: 'today',
  yesterday: 'yesterday',
  daysAgo: (n: number) => `${n} days ago`,
  goalThisWeek: 'This week',
  goalProgress: (n: number, goal: number) => `${n} of ${goal} workouts`,
  goalReached: 'Goal reached',
  goalStreak: (n: number) => `Streak: ${n} ${n === 1 ? 'week' : 'weeks'}`,
  goalNoStreak: 'Reach your goal this week to start a streak.',
  weeklyGoal: 'Weekly goal',
  goalOff: 'Off',
  units: 'Weight unit',
  noteTitle: 'How did it feel?',
  notePlaceholder: 'Optional note, for example: elbow felt fine, +2 reps',
  noteSave: 'Save note',
  noteSaved: 'Note saved',
  noteLabel: 'Workout note',
  backupTitle: 'Backup',
  backupHint: 'Your routines and history live only on this phone. Save a copy now and then.',
  backupExport: 'Save backup file',
  backupImport: 'Restore from file',
  backupFile: 'Backup file',
  backupErrNotJson: 'That file is not a readable backup.',
  backupErrNotBackup: 'That file is not an Intervo backup.',
  backupErrTooBig: 'That file is too large to be an Intervo backup.',
  restoreTitle: 'Restore backup',
  restoreSummary: (routines: number, workouts: number, when: string) => `The file has ${routines} routines and ${workouts} workouts${when ? `, saved ${when}` : ''}.`,
  restoreMerge: 'Add what is missing',
  restoreMergeHint: 'Keeps everything on this phone and adds routines and workouts it does not have yet.',
  restoreReplace: 'Replace everything',
  restoreReplaceHint: 'Removes what is on this phone now and uses the file instead.',
  restoreReplaceTitle: 'Replace everything on this phone?',
  restoreReplaceBody: 'Your current routines, history and settings will be removed and replaced by the file. This can’t be undone.',
  restoreDone: 'Backup restored.',
  metricWeight: 'Heaviest weight',
  remindersTitle: 'Workout reminders',
  remindersToggle: 'Remind me to train',
  remindersTime: 'Reminder time',
  remindersDays: 'Reminder days',
  remindersOn: (when: string) => `Reminders on: ${when}.`,
  remindersUnsupported: 'Reminders need push notifications. On iPhone, add Intervo to your Home Screen and open it from there.',
  remindersDenied: 'Notifications are blocked for Intervo. Allow them in your phone or browser settings, then turn reminders on again.',
  remindersNotConfigured: 'Reminders are not set up on the server yet.',
  remindersFailed: 'Could not reach the server. Check your connection and try again.',
  remindersLost: 'Reminders were on, but this phone is no longer subscribed. Turn them on again.',
  remindersTest: 'Show a test notification',
  remindersTestSent: 'Test sent. If you did not see it, check your notification settings.',
  remindersTestFailed: 'Could not show a notification. Check that notifications are allowed.',
  remindersPrivacy: 'Reminders send only a push address, the time, the days and your time zone to the server. Nothing about your workouts.',
  newRoutine: 'New routine',
  editRoutine: 'Edit routine',
  defaultRoutineName: 'My routine',
  noRoutines: 'No routines yet. Create one, then start it with a single tap.',
  openRoutine: (name: string) => `Edit routine: ${name}`,
  startNamed: (name: string) => `Start ${name}`,
  saveAndStart: 'Save and start',
  discardTitle: 'Discard changes?',
  discardBody: 'Your changes to this routine have not been saved.',
  discard: 'Discard',
  keepEditing: 'Keep editing',
  historyTitle: 'History',
  back: 'Back',
  noHistory: 'No workouts logged yet. Finish or end a workout and it shows up here.',
  noMatches: 'No workouts match these filters.',
  statWorkouts: 'Workouts',
  statWorkTime: 'Work time',
  statSets: 'Sets',
  filters: 'Filters',
  dates: 'Dates',
  last7: 'Last 7 days',
  last30: 'Last 30 days',
  last90: 'Last 90 days',
  allTime: 'All time',
  customRange: 'Custom',
  dateFrom: 'From',
  dateTo: 'To',
  routineFilter: 'Routine',
  exerciseFilter: 'Exercise',
  allRoutines: 'All routines',
  allExercises: 'All exercises',
  resetFilters: 'Reset filters',
  progress: 'Progress',
  metricTime: 'Work time',
  metricSets: 'Sets',
  metricLongest: 'Longest set',
  metricSessions: 'Workouts',
  groupBy: 'Group by',
  groupDay: 'Day',
  groupWeek: 'Week',
  groupMonth: 'Month',
  weekOf: 'Week of',
  chartEmpty: 'Nothing to chart for these filters.',
  tapBar: 'Tap a bar for details.',
  completedTag: 'Completed',
  partialTag: 'Ended early',
  deleteWorkout: 'Delete',
  clearHistory: 'Delete all history',
  showMore: 'Show more',
  roundsDone: (a: number, b: number) => `${a}/${b} rounds`,
} as const;
